### PR TITLE
Remove item templates because now they are included in VS through CLI

### PR DESCRIPTION
**Pull request by Takoooooo**

### CODE REVIEW

**Comment by Mrxx99** [comment]
I think that only works for VS2022, should they still be removed from VS2019 extension?

**Comment by Takoooooo** [comment]
> I think that only works for VS2022, should they still be removed from VS2019 extension?

I guess you are right,will revert. We are planning to deprecate VS2019 support but currently let's revert that

**Comment by Takoooooo** [comment]
Doesen't work currently,seems that only project templates are getting included currently

**Comment by Mrxx99** [comment]
Hm, maybe it does not work for embedded nuget templates...

**Comment by Mrxx99** [comment]
> We are planning to deprecate VS2019

The current VS2019 extension release is already not working, I can't find any templates inside, and even if it worked, the current templates use file scoped namespaces, which are not supported in .NET6 and VS2019 does not support .NET7. So I think the best approach would be to revert the VS2019 extension to the last release where templates were still included in the extension itself and then deprecated it, so it is at least usable but deprecated

**Comment by Mrxx99** [comment]
> Doesen't work currently,seems that only project templates are getting included currently

For me it works in a sample VSIX, that the item template is included in extension (dotnet new template not installed).
But what I noticed and what maybe let you to that conclusion is, that if you open the add new item dialog, initially all folders are shown, but only when the loading text disappears, the folder for my test item template appeared, so if you are not waiting long enough you may have missed it. But will also try to test the Avalonia extension

**Comment by maxkatz6** [comment]
I would vote to drop templates from VS 2019 too. And ask users to use CLI with legacy IDE. Feels like a reasonable trade off.

**Comment by Takoooooo** [comment]
> I would vote to drop templates from VS 2019 too. And ask users to use CLI with legacy IDE. Feels like a reasonable trade off.

I am bringing back project templates for a while,making a last release of vs2019 and deprecating vs2019 as target i think.

**Pull request closed without merging**
