### PR TITLE
Open editor form error list

### LINKED ISSUE #345: Previewer no longer treats .xaml files as design files
### Describe the bug

On 0.10.18.3, .xaml files are no longer recognized as designer files, even if specified as so in the project file.

### To Reproduce

Add a new usercontrol and rename it to a .xaml file

### AvaloniaVS plugin version

0.10.18.3

### Avalonia version

11.0.0-rc-1.1

### Visual Studio version

17.5.1

### Relevant log output

```shell
17:40:45.342 [Information]  Avalonia Package initialized
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by workgroupengineering**
- Restore PR #321
- Fixes #345

### CODE REVIEW

**Comment by workgroupengineering** [comment]
@emmauss When you have spare time, can you test [this](https://dev.azure.com/AvaloniaUI/aa84306f-2981-47b9-8206-edb3bed6250d/_apis/build/builds/37459/artifacts?artifactName=publish&api-version=7.0&%24format=zip)?

**Comment by emmauss** [comment]
> [](https://dev.azure.com/AvaloniaUI/aa84306f-2981-47b9-8206-edb3bed6250d/_apis/build/builds/37459/artifacts?artifactName=publish&api-version=7.0&%24format=zip)?

I'm unable to install your extension. If you want feedback on the issue I reported previously, as long as you can open *.xaml* files, then the issue is resolved.

**Comment by Takoooooo** [comment]
I can't find any difference between master and this PR,designer doesen't open for me when i click on the error in the list. Does it work for you?

**Comment by workgroupengineering** [comment]
> I can't find any difference between master and this PR,designer doesen't open for me when i click on the error in the list. Does it work for you?

With this PR on my machine it works as expected.

**Comment by Takoooooo** [comment]
May you make a gif of how it should work? Maybe i am testing something incorrectly

**Comment by workgroupengineering** [comment]
Yes, but now i am out of office.

**Comment by workgroupengineering** [comment]
## Before
Before

## After
After

## Test Project

[ACTest.zip](https://github.com/AvaloniaUI/AvaloniaVS/files/12249865/ACTest.zip)

**Pull request merged**
