### PR TITLE
VS2022 Support

### LINKED ISSUE #222: Does not install on Visual Studio 2022
Searching for the extension in the IDE doesn't return it, attempting to install it by downloading a .vsix throws the `VSIXInstaller.NoApplicableSKUsException` exception. Here's the installer log: [dd_VSIXInstaller_20211105135926_22cc.log](https://github.com/AvaloniaUI/AvaloniaVS/files/7486143/dd_VSIXInstaller_20211105135926_22cc.log)

### PR DESCRIPTION
**Pull request by Takoooooo**
If you are reading that and have VS2022/VS2019/VS2017 installed please test the accompanying DevOps build artefact, it will speed up merging this PR.
closes #222,#206

### CODE REVIEW

**Comment by Stephanvs** [comment]
I've downloaded the accompanying DevOps build artifact, and installed the VS extension successfully in both:
```
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.0.0```

and:

```
Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.1.0 Preview 1.0
```

And I've verified that the extension works by opening up an .axaml file, and the previewer seems to work.

Hope this helps
Stephanvs

**Comment by grokys** [comment]
Gave this a quick try on VS2022 Preview 1.0 and seems to work well. However, I'm not given the option to install it on VS2019 - this should still be supported, right?

**Comment by Takoooooo** [comment]
> Gave this a quick try on VS2022 Preview 1.0 and seems to work well. However, I'm not given the option to install it on VS2019 - this should still be supported, right?

Yes,and even VS2017 should be supported

**Comment by KieranDevvs** [comment]
> > Gave this a quick try on VS2022 Preview 1.0 and seems to work well. However, I'm not given the option to install it on VS2019 - this should still be supported, right?
> 
> Yes,and even VS2017 should be supported

Id assume this is due to the prerequisite targeting .NET 6 and that not being supported in VS2019 and lower?
Maybe we have to have two extensions?

**Comment by grokys** [comment]
@KieranDevvs where is there a prerequisite targeting NET6? That would indeed cause this problem I guess, only problem is I can't see it!

**Comment by Gillibald** [comment]
Looks like someone found a solution to this: https://cezarypiatek.github.io/post/migrate-vsix-to-vs2022/

**Comment by HavenDV** [comment]
If anyone wants to test the extension in VS2022, here is the file:
image
[AvaloniaVS.zip](https://github.com/AvaloniaUI/AvaloniaVS/files/7681249/AvaloniaVS.zip)

**Comment by KieranDevvs** [comment]
Why has this been closed?

**Pull request closed without merging**
