### PR TITLE
Add text manipulations capabilities:

### PR DESCRIPTION
**Pull request by ShadowDancer**
- renaming start and end tag at same time
- closing tags

This is last part of PR:
https://github.com/kekekeks/Avalonia.Ide/pull/24

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaVS?pullRequest=164) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaVS?pullRequest=164) before we can accept your contribution.<br/><br/>:x: ShadowDancer [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/AvaloniaVS?pullRequest=164)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/AvaloniaVS?pullRequest=164) it.</sub>

**Comment by grokys** [comment]
@ShadowDancer thanks for this, sorry it took so long for me to take a look at it - please feel free to ping me on gitter etc in future, things get lost in the noise sometimes.

Anyway, seems that CI is failing on this PR: https://github.com/AvaloniaUI/AvaloniaVS/pull/164/checks?check_run_id=812910551

> submodules\Avalonia.Ide\src\Avalonia.Ide.CompletionEngine\XmlParser.cs(311,31): Error CS1525: Invalid expression term '='

**Comment by ShadowDancer** [comment]
@grokys 

I've created PR for Avalonia.Ide, which fixes one bug, and fixes build, it is waiting for merge there:
https://github.com/kekekeks/Avalonia.Ide/pull/25

**Comment by grokys** [comment]
@ShadowDancer if you create a branch in your fork of Avalonia.Ide which includes these two commits, you should be able to point this PR at that branch for testing, until those two PRs are merged. Note that this should work even when the submodule URL is targeting upstream because GitHub stores all forks in a single repository.

**Comment by ShadowDancer** [comment]
@grokys I've merged my PR's and pointed this PR there

**Comment by grokys** [comment]
Thanks @ShadowDancer - I'm on vacation for a few days, I'll take a look as soon as I get back!

**Comment by ShadowDancer** [comment]
@grokys what about avalonia.ide? PRS are hanging there.

**Pull request merged**
